services:
  db:
    image: postgres:15
    container_name: flashify-db
    environment:
      POSTGRES_USER: flashify
      POSTGRES_PASSWORD: flashify
      POSTGRES_DB: flashify
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U flashify -d flashify"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: flashify-redis
    ports:
      - "6380:6379"
    restart: always

  backend:
    build: ./back
    container_name: flashify-backend
    env_file:
      - ./back/.env
    ports:
      - "9000:8000"
    volumes:
      - ./uploads:/app/uploads
      - ./back/app:/app/app
      - ./back/gcp-credentials.json:/app/gcp-credentials.json
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    restart: always

  celery-worker:
    build: ./back
    container_name: flashify-worker
    command: celery -A app.worker worker --loglevel=info
    env_file:
      - ./back/.env
    volumes:
      - ./uploads:/app/uploads
      - ./back/app:/app/app
      - ./back/gcp-credentials.json:/app/gcp-credentials.json
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    restart: always

  celery-beat:
    build: ./back
    command: celery -A app.worker beat --loglevel=info
    depends_on:
      - redis
      - db
    env_file:
      - ./back/.env
    volumes:
      - ./back:/app
    restart: unless-stopped

volumes:
  postgres_data: